name: Go Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.1'
    - name: Build
      run: go build -o main.exe -v ./main.go
    - name: Package artifact
      shell: pwsh
      run: |
        mkdir alac
        cp agent.js alac/
        cp agent-arm64.js alac/
        cp config.yaml alac/
        cp README.md alac/
        cp main.exe alac/
        Compress-Archive -Path alac/* -DestinationPath apple-music-downloader-windows.zip
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: apple-music-downloader-windows
        path: apple-music-downloader-windows.zip

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.1'
    - name: Build
      run: go build -o main -v ./main.go
    - name: Package artifact
      run: |
        mkdir alac
        cp agent.js alac/
        cp agent-arm64.js alac/
        cp config.yaml alac/
        cp README.md alac/
        cp main alac/
        zip -r apple-music-downloader-linux.zip alac
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: apple-music-downloader-linux
        path: apple-music-downloader-linux.zip

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.1'
    - name: Build
      run: go build -o main -v ./main.go
    - name: Package artifact
      run: |
        mkdir alac
        cp agent.js alac/
        cp agent-arm64.js alac/
        cp config.yaml alac/
        cp README.md alac/
        cp main alac/
        zip -r apple-music-downloader-macos.zip alac
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: apple-music-downloader-macos
        path: apple-music-downloader-macos.zip

  release:
    runs-on: ubuntu-latest
    needs: [build-windows, build-linux, build-macos]
    permissions:
      contents: write
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
    - name: Create Release and Upload Assets
      uses: softprops/action-gh-release@v2
      with:
        files: artifacts/*/*.zip
        draft: true